# Generated by Django 5.1.3 on 2025-02-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_friendrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
    ]
