# Generated by Django 5.1.3 on 2025-02-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_friendrequest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
    ]
