# Generated by Django 5.1.3 on 2025-02-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
