# Generated by Django 5.1.3 on 2025-02-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_report_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicgroup',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
