# Generated by Django 5.1.3 on 2025-02-17 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_grouppoll_grouppollchoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppollchoice',
            name='poll',
        ),
        migrations.AddField(
            model_name='publicgroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupPoll',
        ),
        migrations.DeleteModel(
            name='GroupPollChoice',
        ),
    ]
